### ISSUE TITLE
Test apps for EMC testing and serial speed

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tillitis-key1-apps#10]
A modified signer app with no touch requirements and a host software that loads and then just signs messages forever. For EMC test and serial speed test.

Signatures need to be validated by the host part to see if something goes wrong.

**Comment by quite** [comment]
I have something in branch `test-loop`. Then I ran into https://github.com/tillitis/tillitis-key1/issues/24

**Comment by quite** [comment]
We have moved up to 62500 bps and consider it stable. The `test-loop.sh` script in the `test-loop` branch branch here https://github.com/tillitis/tillitis-key1-apps/blob/test-loop/test-loop.sh uploads the signing app, and proceeds to sign 128 bytes of random data forever. Have a look @cibomahto 

Not sure how we move forward with EMC, but we have something ready to run there!

**Comment by quite** [comment]
Perhaps it should all be packaged in some way, for easy plug-and-pray. I'll be of assistance, but we'd need info about test env etc etc

**Comment by cibomahto** [comment]
@quite Great- i'll try to get it running today, ideally I'd like to get some hundreds of hours of testing in.

For EMC, we'll need to provide an entire setup (device, cable, computer), that the test house can plug in and start with very simple instructions. The computer side of the test will also need to provide a simple (ok/fail) type of feedback to the test operator, so that it's clear if something fails during susceptibility testing.

**Comment by cibomahto** [comment]
I added support for running the communication test under the docker image:
https://github.com/tillitis/tillitis-key1/compare/main...communication_test_automation

This also required a change to the test-loop script:
https://github.com/tillitis/tillitis-key1-apps/commit/70292c457b2d959ed2b676e8bd270649987cce61

If you clone both repos in a common directory, then you can launch the test script like this:
cd tillitis-key1/contrib
make
make USB_DEVICE=/dev/ttyACM0 test-loop

**Comment by cibomahto** [comment]
Closing this since the original scope of work is complete

**Comment by quite** [comment]
Actually closing this.
