### ISSUE TITLE
[linux] tk-sign app hangs during long term stress testing

### ISSUE THREAD

**Issue by cibomahto** [tillitis/tillitis-key1-apps#20]
Using the test-loop.sh script from the [communication test branch](https://github.com/tillitis/tillitis-key1-apps/tree/communication_test_automation), the test-loop.sh eventually hangs after some number of signatures, for example:

    loop count: 645, seconds passed: 362
    Auto-detected serial port /dev/ttyACM1
    Connecting to device on serial port /dev/ttyACM1 ...
    Public Key from device (UID 00010:20:3:04050607): ebb95cac6cb6fb662a231363cfeb6d5a132866ed2fee55dc8efc7bc8c7726ffe
    Sending a 128 bytes message for signing.

or: 

    loop count: 235, seconds passed: 132
    Auto-detected serial port /dev/ttyACM2
    Connecting to device on serial port /dev/ttyACM2 ...
    Public Key from device (UID 00010:20:3:04050607): ebb95cac6cb6fb662a231363cfeb6d5a132866ed2fee55dc8efc7bc8c7726ffe
    Sending a 128 bytes message for signing.
    Signature over message by device: 70dc2638de2cd1d3e09040d511f36ece9ebc40a7205a9c458216ccf8bd4fa3a635a8a018e77e563bab3f2ff687377b6d13d404326905df27f0b70ccdb15c6b01
    Signature verified.
    loop count: 236, seconds passed: 133
    Auto-detected serial port /dev/ttyACM2
    Connecting to device on serial port /dev/ttyACM2 ...

This testing was performed on a laptop running Debian, with the signing apps running from Ubuntu docker containers. Four mta1-usb-v1 devices were prepared in the same way as described in #19. Three devices were connected to the laptop using a USB 3 hub, and the fourth directly to a USB a port (previous testing did not uncover any correlation between which port the device was connected to, and the eventual failure). The docker container was built from the [communication test branch](https://github.com/tillitis/tillitis-key1/tree/communication_test_automation/contrib) of the tillitis-key1 repository:

    cd contrib
    make build

Then, a test-loop script was run for each of the four connected keys, using make to start the scripts:

    USB_DEVICE=/dev/ttyACM0 make test-loop

All four scripts stopped after a short number of iterations, hanging in tk-sign after displaying one of two messages, either 'Sending a 128 bytes message for signing.', or 'Connecting to device on serial port /dev/ttyACM2 ...':

![image](https://user-images.githubusercontent.com/44493/199697985-fa48a79e-df51-4a48-a669-f9e5e8ad3973.png)

This likely has the same cause as #19 , however the point where it hangs happened to be different in linux, so I reported it as a separate issue. There is also a chance this is related to running the script in a container, so it might be good to try this again without containers (I can do that if it's helpful).

**Comment by dehanj** [comment]
Most likely same issue as #19.
I saw quite different results depending on OS, but after the fix I cannot reproduce it on any platform.
