### ISSUE TITLE
macos: the serial pkg's enumeration can't be built with CGO_ENABLED=0 

### ISSUE THREAD

**Issue by quite** [tillitis/tillitis-key1-apps#29]
From: https://pkg.go.dev/go.bug.st/serial

> This library tries to avoid the use of the "C" package (and consequently the need of cgo) to simplify cross compiling. Unfortunately the USB enumeration package for darwin (MacOSX) requires cgo to access the IOKit framework. This means that if you need USB enumeration on darwin you're forced to use cgo.

**Comment by dehanj** [comment]
We have to live with this.
