### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tillitis-key1-apps#37]
At least do a complete build and yell if anything fails.

**Comment by quite** [comment]
I got some basic CI running now, it does make all, lint go and check C code formatting. On push to main, and on new PR (draft or not).

I think I want to add some kind of check for changes that causes signer.bin to change. By storing the currect expected hash in the repo maybe?

**Comment by quite** [comment]
apps/signer/app.bin.sha256 and CI check coming here: https://github.com/tillitis/tillitis-key1-apps/pull/55

**Comment by quite** [comment]
The signer app hash check was merged.
