### ISSUE TITLE
tkey-ssh-agent: make less assumptions on systemd availability

### ISSUE THREAD

**Issue by omnivagant** [tillitis/tillitis-key1-apps#50]
`make install` [want to install a systemd service file](https://github.com/tillitis/tillitis-key1-apps/blob/main/Makefile#L20) with no opt-in/out.

~~[tkey-ssh-agent(1)](https://github.com/tillitis/tillitis-key1-apps/blob/main/system/tkey-ssh-agent.1) make some assumptions on systemd availability.~~ *(edit by quite: it no longer does)*

**Comment by mchack-work** [comment]
Resolved elsewhere. Closing.
