### ISSUE TITLE
tkey-ssh-agent: documentation and flags

### ISSUE THREAD

**Issue by omnivagant** [tillitis/tillitis-key1-apps#51]
All flags should be documented in the man page, not just the help output.

Make sure flags don't overlap with other ssh-agent implementations, like OpenSSH:
```
-k      Kill the current agent (given by the SSH_AGENT_PID environment variable).
```

**Comment by quite** [comment]
I agree. It would be great if the man-page was generated, especially to automatically get the flags defined in code in there automatically.

And the takeover of `-k` was unfortunate, too. Not sure what the right move is now, just change it maybe.

**Comment by quite** [comment]
We'll change to `-p` as the short for `--show-pubkey`.

**Comment by quite** [comment]
And now the man page got an update.
