### ISSUE TITLE
Break out Go packages

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tillitis-key1-apps#85]
Break out our two Go packages to their own repos:
- [ ] tk1
- [ ] tk1sign

**Comment by quite** [comment]
For all the breaking out of items from the apps repo I suggest to really try to maintain git history. It ought to be possible to start with a copy of the repo and then `git rm` all that should not be part of it, in this case here everything that is the tk1 or tk1sign package respectively.

**Comment by quite** [comment]
People seem to make the effort to not only remove current files, but to prune the history of them. https://stackoverflow.com/questions/61062501/split-git-repository-and-only-keep-history-of-remaining-files Not sure if it's worth the effort (or don't see any immediate caveat with *not* doing so either).

**Comment by mchack-work** [comment]
Merged.
