### ISSUE TITLE
I/O and debug function confusion

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tillitis-key1-apps#9]
The debug functions `putchar()`, `puts()` et cetera currently only work on the QEMU debug port we added. This is confusing.

I suggest we change the names of these function to `debug_*()` or `qemu_*()` or something and also include real `puts()` et cetera that uses the UART.

**Comment by secworks** [comment]
I suggest using qemu_*() for functions only used in, makes sense in the QEMU model. It would make it very explicit and hard to misunderstand. I hope.

**Comment by quite** [comment]
This is similar in the fw for those functions that output to "htif console".

**Comment by mchack-work** [comment]
Merged in main repo and -apps.
