### ISSUE TITLE
Question: Why use `RM=/bin/rm` in certain places and not others?

### ISSUE THREAD

**Issue by sagehane** [tillitis/tillitis-key1-apps#91]
Distros that don't follow the FHS like NixOS or Guix have issues running `make clean` as it currently is.
If there's no real reason to for using `RM=/bin/rm`, it would be nice to avoid referring to `/bin`.
Also confusing is that there are a few scripts that don't follow the same convention.

Makefiles seem to use `RM=/bin/rm`:
https://github.com/tillitis/tillitis-key1-apps/blob/2261f0c9a156e43246dff29c033ece5e6d3ec161/Makefile#L1
https://github.com/tillitis/tillitis-key1-apps/blob/2261f0c9a156e43246dff29c033ece5e6d3ec161/apps/Makefile#L27

Shell scripts seem to use `rm`:
https://github.com/tillitis/tillitis-key1-apps/blob/2261f0c9a156e43246dff29c033ece5e6d3ec161/debian/build-pkg.sh#L23
https://github.com/tillitis/tillitis-key1-apps/blob/2261f0c9a156e43246dff29c033ece5e6d3ec161/test/attic/test-loop.sh#L41
https://github.com/tillitis/tillitis-key1-apps/blob/2261f0c9a156e43246dff29c033ece5e6d3ec161/test/run#L23

**Comment by sagehane** [comment]
The `tkey-libs` repo also uses `RM=/bin/rm`:
https://github.com/tillitis/tkey-libs/blob/3f4fd17e8f15461e8ec0913a151d26c3b4831b28/Makefile#L24

However, the `tkey-verification` repo just uses `rm`:
https://github.com/tillitis/tkey-verification/blob/b0652a94e5b40060bc05d419d3f9f6effcd5b23c/Makefile

**Comment by dehanj** [comment]
Hi @sagehane,

The reason for using `/bin/rm` was an attempt to make it work regardless of aliases, but we find it more important that it is convinient to work with our repo on different distros - so we will change to just `rm`. 

However, we require signed commits in our repositories. So I will take the diff from your [PR](https://github.com/tillitis/tillitis-key1-apps/pull/92) and apply it to a branch of my own, set you as author and sign it for you to create a PR. Hope that is fine.

**Comment by sagehane** [comment]
That's fine. Just so you know, my commit is signed with Git's SSH signing feature, but I understand that's not well supported on Github. Thanks for being considerate for other distros.
